FROM ghcr.io/evroon/bracket-backend:v2.2.5

USER root

COPY --chown=bracket:bracket . /app

WORKDIR /app

USER bracket

HEALTHCHECK --interval=10s --timeout=5s --retries=5 \
  CMD wget --spider -q http://localhost:8400/ping || exit 1

CMD ["pipenv", "run", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "bracket.app:app", "--bind", "0.0.0.0:8400", "--workers", "1"]
