// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
  ActivateNextStageTournamentsTournamentIdStagesActivatePostData,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
  CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostData,
  CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostErrors,
  CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostResponses,
  ChangeStatusTournamentsTournamentIdChangeStatusPostData,
  ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
  ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
  CreateClubUserClubsClubIdUsersPostData,
  CreateClubUserClubsClubIdUsersPostErrors,
  CreateClubUserClubsClubIdUsersPostResponses,
  CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostData,
  CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostErrors,
  CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostResponses,
  CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostData,
  CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostErrors,
  CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostResponses,
  CreateCourtTournamentsTournamentIdCourtsPostData,
  CreateCourtTournamentsTournamentIdCourtsPostErrors,
  CreateCourtTournamentsTournamentIdCourtsPostResponses,
  CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostData,
  CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostErrors,
  CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostResponses,
  CreateMatchTournamentsTournamentIdMatchesPostData,
  CreateMatchTournamentsTournamentIdMatchesPostErrors,
  CreateMatchTournamentsTournamentIdMatchesPostResponses,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostData,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostData,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
  CreateNewClubClubsPostData,
  CreateNewClubClubsPostErrors,
  CreateNewClubClubsPostResponses,
  CreateRankingTournamentsTournamentIdRankingsPostData,
  CreateRankingTournamentsTournamentIdRankingsPostErrors,
  CreateRankingTournamentsTournamentIdRankingsPostResponses,
  CreateRoundTournamentsTournamentIdRoundsPostData,
  CreateRoundTournamentsTournamentIdRoundsPostErrors,
  CreateRoundTournamentsTournamentIdRoundsPostResponses,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostData,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
  CreateStageItemTournamentsTournamentIdStageItemsPostData,
  CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
  CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
  CreateStageTournamentsTournamentIdStagesPostData,
  CreateStageTournamentsTournamentIdStagesPostErrors,
  CreateStageTournamentsTournamentIdStagesPostResponses,
  CreateTeamTournamentsTournamentIdTeamsPostData,
  CreateTeamTournamentsTournamentIdTeamsPostErrors,
  CreateTeamTournamentsTournamentIdTeamsPostResponses,
  CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostData,
  CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostErrors,
  CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostResponses,
  CreateTournamentTournamentsPostData,
  CreateTournamentTournamentsPostErrors,
  CreateTournamentTournamentsPostResponses,
  CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostData,
  CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostErrors,
  CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostResponses,
  DeleteClubClubsClubIdDeleteData,
  DeleteClubClubsClubIdDeleteErrors,
  DeleteClubClubsClubIdDeleteResponses,
  DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteData,
  DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteErrors,
  DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteResponses,
  DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteData,
  DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteErrors,
  DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteResponses,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteData,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
  DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteData,
  DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteErrors,
  DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteResponses,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteData,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteData,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteData,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteData,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteData,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteData,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteData,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
  DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteData,
  DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteErrors,
  DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteResponses,
  DeleteTournamentTournamentsTournamentIdDeleteData,
  DeleteTournamentTournamentsTournamentIdDeleteErrors,
  DeleteTournamentTournamentsTournamentIdDeleteResponses,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetData,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
  GetClubsClubsGetData,
  GetClubsClubsGetResponses,
  GetClubUsersClubsClubIdUsersGetData,
  GetClubUsersClubsClubIdUsersGetErrors,
  GetClubUsersClubsClubIdUsersGetResponses,
  GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetData,
  GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetErrors,
  GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetResponses,
  GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetData,
  GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetErrors,
  GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetResponses,
  GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetData,
  GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetErrors,
  GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetResponses,
  GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetData,
  GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetErrors,
  GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetResponses,
  GetCompetitionsTournamentsTournamentIdCompetitionsGetData,
  GetCompetitionsTournamentsTournamentIdCompetitionsGetErrors,
  GetCompetitionsTournamentsTournamentIdCompetitionsGetResponses,
  GetCourtsTournamentsTournamentIdCourtsGetData,
  GetCourtsTournamentsTournamentIdCourtsGetErrors,
  GetCourtsTournamentsTournamentIdCourtsGetResponses,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
  GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetData,
  GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetErrors,
  GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetResponses,
  GetMetricsMetricsGetData,
  GetMetricsMetricsGetResponses,
  GetMeUsersUserIdGetData,
  GetMeUsersUserIdGetErrors,
  GetMeUsersUserIdGetResponses,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetData,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
  GetOverallStandingsTournamentsTournamentIdOverallStandingsGetData,
  GetOverallStandingsTournamentsTournamentIdOverallStandingsGetErrors,
  GetOverallStandingsTournamentsTournamentIdOverallStandingsGetResponses,
  GetPlayersTournamentsTournamentIdPlayersGetData,
  GetPlayersTournamentsTournamentIdPlayersGetErrors,
  GetPlayersTournamentsTournamentIdPlayersGetResponses,
  GetRankingsTournamentsTournamentIdRankingsGetData,
  GetRankingsTournamentsTournamentIdRankingsGetErrors,
  GetRankingsTournamentsTournamentIdRankingsGetResponses,
  GetStagesTournamentsTournamentIdStagesGetData,
  GetStagesTournamentsTournamentIdStagesGetErrors,
  GetStagesTournamentsTournamentIdStagesGetResponses,
  GetTeamsTournamentsTournamentIdTeamsGetData,
  GetTeamsTournamentsTournamentIdTeamsGetErrors,
  GetTeamsTournamentsTournamentIdTeamsGetResponses,
  GetTournamentsTournamentsGetData,
  GetTournamentsTournamentsGetErrors,
  GetTournamentsTournamentsGetResponses,
  GetTournamentTournamentsTournamentIdGetData,
  GetTournamentTournamentsTournamentIdGetErrors,
  GetTournamentTournamentsTournamentIdGetResponses,
  GetUserUsersMeGetData,
  GetUserUsersMeGetResponses,
  ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetData,
  ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetErrors,
  ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetResponses,
  ListTournamentMatchEventsTournamentsTournamentIdEventsGetData,
  ListTournamentMatchEventsTournamentsTournamentIdEventsGetErrors,
  ListTournamentMatchEventsTournamentsTournamentIdEventsGetResponses,
  ListTournamentSponsorsTournamentsTournamentIdSponsorsGetData,
  ListTournamentSponsorsTournamentsTournamentIdSponsorsGetErrors,
  ListTournamentSponsorsTournamentsTournamentIdSponsorsGetResponses,
  LoginForAccessTokenTokenPostData,
  LoginForAccessTokenTokenPostErrors,
  LoginForAccessTokenTokenPostResponses,
  PingPingGetData,
  PingPingGetResponses,
  PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetData,
  PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetErrors,
  PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetResponses,
  PutUserPasswordUsersUserIdPasswordPutData,
  PutUserPasswordUsersUserIdPasswordPutErrors,
  PutUserPasswordUsersUserIdPasswordPutResponses,
  RegisterDemoUserUsersRegisterDemoPostData,
  RegisterDemoUserUsersRegisterDemoPostErrors,
  RegisterDemoUserUsersRegisterDemoPostResponses,
  RegisterUserUsersRegisterPostData,
  RegisterUserUsersRegisterPostErrors,
  RegisterUserUsersRegisterPostResponses,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostData,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostData,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
  SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutData,
  SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutErrors,
  SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutResponses,
  SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutData,
  SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutErrors,
  SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutResponses,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
  TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostData,
  TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostErrors,
  TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostResponses,
  UpdateClubClubsClubIdPutData,
  UpdateClubClubsClubIdPutErrors,
  UpdateClubClubsClubIdPutResponses,
  UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutData,
  UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutErrors,
  UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutResponses,
  UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutData,
  UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutErrors,
  UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutResponses,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutData,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
  UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutData,
  UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutErrors,
  UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutResponses,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutData,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutData,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
  UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutData,
  UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutErrors,
  UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutResponses,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutData,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutData,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutData,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
  UpdateStageTournamentsTournamentIdStagesStageIdPutData,
  UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
  UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutData,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostData,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
  UpdateTournamentByIdTournamentsTournamentIdPutData,
  UpdateTournamentByIdTournamentsTournamentIdPutErrors,
  UpdateTournamentByIdTournamentsTournamentIdPutResponses,
  UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutData,
  UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutErrors,
  UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutResponses,
  UpdateUserDetailsUsersUserIdPutData,
  UpdateUserDetailsUsersUserIdPutErrors,
  UpdateUserDetailsUsersUserIdPutResponses,
  UploadLogoTournamentsTournamentIdLogoPostData,
  UploadLogoTournamentsTournamentIdLogoPostErrors,
  UploadLogoTournamentsTournamentIdLogoPostResponses,
  UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostData,
  UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostErrors,
  UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Clubs
 */
export const getClubsClubsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetClubsClubsGetData, ThrowOnError>,
): RequestResult<GetClubsClubsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetClubsClubsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs',
    ...options,
  });

/**
 * Create New Club
 */
export const createNewClubClubsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateNewClubClubsPostData, ThrowOnError>,
): RequestResult<CreateNewClubClubsPostResponses, CreateNewClubClubsPostErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateNewClubClubsPostResponses,
    CreateNewClubClubsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Club
 */
export const deleteClubClubsClubIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteClubClubsClubIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteClubClubsClubIdDeleteResponses,
  DeleteClubClubsClubIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteClubClubsClubIdDeleteResponses,
    DeleteClubClubsClubIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}',
    ...options,
  });

/**
 * Update Club
 */
export const updateClubClubsClubIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateClubClubsClubIdPutData, ThrowOnError>,
): RequestResult<UpdateClubClubsClubIdPutResponses, UpdateClubClubsClubIdPutErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateClubClubsClubIdPutResponses,
    UpdateClubClubsClubIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Club Users
 */
export const getClubUsersClubsClubIdUsersGet = <ThrowOnError extends boolean = false>(
  options: Options<GetClubUsersClubsClubIdUsersGetData, ThrowOnError>,
): RequestResult<
  GetClubUsersClubsClubIdUsersGetResponses,
  GetClubUsersClubsClubIdUsersGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetClubUsersClubsClubIdUsersGetResponses,
    GetClubUsersClubsClubIdUsersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}/users',
    ...options,
  });

/**
 * Create Club User
 */
export const createClubUserClubsClubIdUsersPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateClubUserClubsClubIdUsersPostData, ThrowOnError>,
): RequestResult<
  CreateClubUserClubsClubIdUsersPostResponses,
  CreateClubUserClubsClubIdUsersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateClubUserClubsClubIdUsersPostResponses,
    CreateClubUserClubsClubIdUsersPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Metrics
 */
export const getMetricsMetricsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMetricsMetricsGetData, ThrowOnError>,
): RequestResult<GetMetricsMetricsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetMetricsMetricsGetResponses, unknown, ThrowOnError>({
    responseType: 'text',
    url: '/metrics',
    ...options,
  });

/**
 * Healthcheck ping
 */
export const pingPingGet = <ThrowOnError extends boolean = false>(
  options?: Options<PingPingGetData, ThrowOnError>,
): RequestResult<PingPingGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<PingPingGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/ping',
    ...options,
  });

/**
 * Login For Access Token
 */
export const loginForAccessTokenTokenPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginForAccessTokenTokenPostData, ThrowOnError>,
): RequestResult<
  LoginForAccessTokenTokenPostResponses,
  LoginForAccessTokenTokenPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    LoginForAccessTokenTokenPostResponses,
    LoginForAccessTokenTokenPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });

/**
 * Get Tournaments
 */
export const getTournamentsTournamentsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTournamentsTournamentsGetData, ThrowOnError>,
): RequestResult<
  GetTournamentsTournamentsGetResponses,
  GetTournamentsTournamentsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetTournamentsTournamentsGetResponses,
    GetTournamentsTournamentsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments',
    ...options,
  });

/**
 * Create Tournament
 */
export const createTournamentTournamentsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTournamentTournamentsPostData, ThrowOnError>,
): RequestResult<
  CreateTournamentTournamentsPostResponses,
  CreateTournamentTournamentsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTournamentTournamentsPostResponses,
    CreateTournamentTournamentsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Tournament
 */
export const deleteTournamentTournamentsTournamentIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTournamentTournamentsTournamentIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteTournamentTournamentsTournamentIdDeleteResponses,
  DeleteTournamentTournamentsTournamentIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTournamentTournamentsTournamentIdDeleteResponses,
    DeleteTournamentTournamentsTournamentIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Get Tournament
 */
export const getTournamentTournamentsTournamentIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTournamentTournamentsTournamentIdGetData, ThrowOnError>,
): RequestResult<
  GetTournamentTournamentsTournamentIdGetResponses,
  GetTournamentTournamentsTournamentIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTournamentTournamentsTournamentIdGetResponses,
    GetTournamentTournamentsTournamentIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Update Tournament By Id
 */
export const updateTournamentByIdTournamentsTournamentIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTournamentByIdTournamentsTournamentIdPutData, ThrowOnError>,
): RequestResult<
  UpdateTournamentByIdTournamentsTournamentIdPutResponses,
  UpdateTournamentByIdTournamentsTournamentIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateTournamentByIdTournamentsTournamentIdPutResponses,
    UpdateTournamentByIdTournamentsTournamentIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Available Inputs
 */
export const getAvailableInputsTournamentsTournamentIdAvailableInputsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAvailableInputsTournamentsTournamentIdAvailableInputsGetData, ThrowOnError>,
): RequestResult<
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
    GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/available_inputs',
    ...options,
  });

/**
 * Change Status
 *
 * Make a tournament archived or non-archived.
 */
export const changeStatusTournamentsTournamentIdChangeStatusPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChangeStatusTournamentsTournamentIdChangeStatusPostData, ThrowOnError>,
): RequestResult<
  ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
  ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
    ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/change-status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Competitions
 */
export const getCompetitionsTournamentsTournamentIdCompetitionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCompetitionsTournamentsTournamentIdCompetitionsGetData, ThrowOnError>,
): RequestResult<
  GetCompetitionsTournamentsTournamentIdCompetitionsGetResponses,
  GetCompetitionsTournamentsTournamentIdCompetitionsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCompetitionsTournamentsTournamentIdCompetitionsGetResponses,
    GetCompetitionsTournamentsTournamentIdCompetitionsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/competitions',
    ...options,
  });

/**
 * Create Competition Route
 */
export const createCompetitionRouteTournamentsTournamentIdCompetitionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostData, ThrowOnError>,
): RequestResult<
  CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostResponses,
  CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostResponses,
    CreateCompetitionRouteTournamentsTournamentIdCompetitionsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/competitions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Competition Route
 */
export const deleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteResponses,
  DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteResponses,
    DeleteCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/competitions/{competition_id}',
    ...options,
  });

/**
 * Get Competition By Id
 */
export const getCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetData,
    ThrowOnError
  >,
): RequestResult<
  GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetResponses,
  GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetResponses,
    GetCompetitionByIdTournamentsTournamentIdCompetitionsCompetitionIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/competitions/{competition_id}',
    ...options,
  });

/**
 * Update Competition Route
 */
export const updateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutResponses,
  UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutResponses,
    UpdateCompetitionRouteTournamentsTournamentIdCompetitionsCompetitionIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/competitions/{competition_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Competition Disciplines
 */
export const getCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetData,
      ThrowOnError
    >,
  ): RequestResult<
    GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetResponses,
    GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetResponses,
      GetCompetitionDisciplinesTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesGetErrors,
      ThrowOnError
    >({
      responseType: 'json',
      url: '/tournaments/{tournament_id}/competitions/{competition_id}/disciplines',
      ...options,
    });

/**
 * Create Competition Discipline
 */
export const createCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostData,
      ThrowOnError
    >,
  ): RequestResult<
    CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostResponses,
    CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostResponses,
      CreateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesPostErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/competitions/{competition_id}/disciplines',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Delete Competition Discipline
 */
export const deleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteData,
      ThrowOnError
    >,
  ): RequestResult<
    DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteResponses,
    DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteErrors,
    ThrowOnError
  > =>
    (options.client ?? client).delete<
      DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteResponses,
      DeleteCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdDeleteErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/competitions/{competition_id}/disciplines/{discipline_id}',
      ...options,
    });

/**
 * Update Competition Discipline
 */
export const updateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutResponses,
    UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutErrors,
    ThrowOnError
  > =>
    (options.client ?? client).put<
      UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutResponses,
      UpdateCompetitionDisciplineTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdPutErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/competitions/{competition_id}/disciplines/{discipline_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Calculate Competition Results
 */
export const calculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostData,
      ThrowOnError
    >,
  ): RequestResult<
    CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostResponses,
    CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostResponses,
      CalculateCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdCalculatePostErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/competitions/{competition_id}/disciplines/{discipline_id}/calculate',
      ...options,
    });

/**
 * Get Competition Results
 */
export const getCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetData,
      ThrowOnError
    >,
  ): RequestResult<
    GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetResponses,
    GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetResponses,
      GetCompetitionResultsTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsGetErrors,
      ThrowOnError
    >({
      responseType: 'json',
      url: '/tournaments/{tournament_id}/competitions/{competition_id}/disciplines/{discipline_id}/results',
      ...options,
    });

/**
 * Set Competition Result
 */
export const setCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutData,
      ThrowOnError
    >,
  ): RequestResult<
    SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutResponses,
    SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutErrors,
    ThrowOnError
  > =>
    (options.client ?? client).put<
      SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutResponses,
      SetCompetitionResultTournamentsTournamentIdCompetitionsCompetitionIdDisciplinesDisciplineIdResultsPutErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/competitions/{competition_id}/disciplines/{discipline_id}/results',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Get Competition Scoring
 */
export const getCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetData,
    ThrowOnError
  >,
): RequestResult<
  GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetResponses,
  GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetResponses,
    GetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/competitions/{competition_id}/scoring',
    ...options,
  });

/**
 * Set Competition Scoring
 */
export const setCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutData,
    ThrowOnError
  >,
): RequestResult<
  SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutResponses,
  SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutResponses,
    SetCompetitionScoringTournamentsTournamentIdCompetitionsCompetitionIdScoringPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/competitions/{competition_id}/scoring',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Courts
 */
export const getCourtsTournamentsTournamentIdCourtsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCourtsTournamentsTournamentIdCourtsGetData, ThrowOnError>,
): RequestResult<
  GetCourtsTournamentsTournamentIdCourtsGetResponses,
  GetCourtsTournamentsTournamentIdCourtsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCourtsTournamentsTournamentIdCourtsGetResponses,
    GetCourtsTournamentsTournamentIdCourtsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/courts',
    ...options,
  });

/**
 * Create Court
 */
export const createCourtTournamentsTournamentIdCourtsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCourtTournamentsTournamentIdCourtsPostData, ThrowOnError>,
): RequestResult<
  CreateCourtTournamentsTournamentIdCourtsPostResponses,
  CreateCourtTournamentsTournamentIdCourtsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCourtTournamentsTournamentIdCourtsPostResponses,
    CreateCourtTournamentsTournamentIdCourtsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Court
 */
export const deleteCourtTournamentsTournamentIdCourtsCourtIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
    DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
  });

/**
 * Update Court By Id
 */
export const updateCourtByIdTournamentsTournamentIdCourtsCourtIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutData, ThrowOnError>,
): RequestResult<
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
    UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Tournament Match Events
 */
export const listTournamentMatchEventsTournamentsTournamentIdEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListTournamentMatchEventsTournamentsTournamentIdEventsGetData, ThrowOnError>,
): RequestResult<
  ListTournamentMatchEventsTournamentsTournamentIdEventsGetResponses,
  ListTournamentMatchEventsTournamentsTournamentIdEventsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListTournamentMatchEventsTournamentsTournamentIdEventsGetResponses,
    ListTournamentMatchEventsTournamentsTournamentIdEventsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/events',
    ...options,
  });

/**
 * Upload Logo
 */
export const uploadLogoTournamentsTournamentIdLogoPost = <ThrowOnError extends boolean = false>(
  options: Options<UploadLogoTournamentsTournamentIdLogoPostData, ThrowOnError>,
): RequestResult<
  UploadLogoTournamentsTournamentIdLogoPostResponses,
  UploadLogoTournamentsTournamentIdLogoPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UploadLogoTournamentsTournamentIdLogoPostResponses,
    UploadLogoTournamentsTournamentIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Match
 */
export const createMatchTournamentsTournamentIdMatchesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateMatchTournamentsTournamentIdMatchesPostData, ThrowOnError>,
): RequestResult<
  CreateMatchTournamentsTournamentIdMatchesPostResponses,
  CreateMatchTournamentsTournamentIdMatchesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateMatchTournamentsTournamentIdMatchesPostResponses,
    CreateMatchTournamentsTournamentIdMatchesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Match
 */
export const deleteMatchTournamentsTournamentIdMatchesMatchIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses,
    DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}',
    ...options,
  });

/**
 * Update Match By Id
 */
export const updateMatchByIdTournamentsTournamentIdMatchesMatchIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutData, ThrowOnError>,
): RequestResult<
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
    UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Match Events
 */
export const listMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetData, ThrowOnError>,
): RequestResult<
  ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetResponses,
  ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetResponses,
    ListMatchEventsTournamentsTournamentIdMatchesMatchIdEventsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/events',
    ...options,
  });

/**
 * Create Event
 */
export const createEventTournamentsTournamentIdMatchesMatchIdEventsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostData, ThrowOnError>,
): RequestResult<
  CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostResponses,
  CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostResponses,
    CreateEventTournamentsTournamentIdMatchesMatchIdEventsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/events',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Event
 */
export const deleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteResponses,
  DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteResponses,
    DeleteEventTournamentsTournamentIdMatchesMatchIdEventsEventIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/events/{event_id}',
    ...options,
  });

/**
 * Update Event
 */
export const updateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutResponses,
  UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutResponses,
    UpdateEventTournamentsTournamentIdMatchesMatchIdEventsEventIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/events/{event_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Match Penalty Catalog
 */
export const getMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetData,
    ThrowOnError
  >,
): RequestResult<
  GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetResponses,
  GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetResponses,
    GetMatchPenaltyCatalogTournamentsTournamentIdMatchesMatchIdPenaltiesCatalogGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/penalties/catalog',
    ...options,
  });

/**
 * Transition Match Phase By Id
 */
export const transitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostData,
    ThrowOnError
  >,
): RequestResult<
  TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostResponses,
  TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostResponses,
    TransitionMatchPhaseByIdTournamentsTournamentIdMatchesMatchIdPhasePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/phase',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reschedule Match
 */
export const rescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostData,
    ThrowOnError
  >,
): RequestResult<
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/reschedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Next Stage Rankings
 *
 * Get the rankings for the stage items in this stage.
 */
export const getNextStageRankingsTournamentsTournamentIdNextStageRankingsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetData,
    ThrowOnError
  >,
): RequestResult<
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/next_stage_rankings',
    ...options,
  });

/**
 * Get Overall Standings
 */
export const getOverallStandingsTournamentsTournamentIdOverallStandingsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOverallStandingsTournamentsTournamentIdOverallStandingsGetData, ThrowOnError>,
): RequestResult<
  GetOverallStandingsTournamentsTournamentIdOverallStandingsGetResponses,
  GetOverallStandingsTournamentsTournamentIdOverallStandingsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOverallStandingsTournamentsTournamentIdOverallStandingsGetResponses,
    GetOverallStandingsTournamentsTournamentIdOverallStandingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/overall_standings',
    ...options,
  });

/**
 * Player Statistics
 */
export const playerStatisticsTournamentsTournamentIdPlayerStatisticsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetData, ThrowOnError>,
): RequestResult<
  PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetResponses,
  PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetResponses,
    PlayerStatisticsTournamentsTournamentIdPlayerStatisticsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/player_statistics',
    ...options,
  });

/**
 * Get Players
 */
export const getPlayersTournamentsTournamentIdPlayersGet = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayersTournamentsTournamentIdPlayersGetData, ThrowOnError>,
): RequestResult<
  GetPlayersTournamentsTournamentIdPlayersGetResponses,
  GetPlayersTournamentsTournamentIdPlayersGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPlayersTournamentsTournamentIdPlayersGetResponses,
    GetPlayersTournamentsTournamentIdPlayersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players',
    ...options,
  });

/**
 * Create Single Player
 */
export const createSinglePlayerTournamentsTournamentIdPlayersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSinglePlayerTournamentsTournamentIdPlayersPostData, ThrowOnError>,
): RequestResult<
  CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
    CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Player
 */
export const deletePlayerTournamentsTournamentIdPlayersPlayerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteData, ThrowOnError>,
): RequestResult<
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
    DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players/{player_id}',
    ...options,
  });

/**
 * Update Player By Id
 */
export const updatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutData, ThrowOnError>,
): RequestResult<
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
    UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players/{player_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Player Team
 */
export const updatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutData, ThrowOnError>,
): RequestResult<
  UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutResponses,
  UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutResponses,
    UpdatePlayerTeamTournamentsTournamentIdPlayersPlayerIdTeamPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players/{player_id}/team',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Multiple Players
 */
export const createMultiplePlayersTournamentsTournamentIdPlayersMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostData, ThrowOnError>,
): RequestResult<
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
    CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Rankings
 */
export const getRankingsTournamentsTournamentIdRankingsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetRankingsTournamentsTournamentIdRankingsGetData, ThrowOnError>,
): RequestResult<
  GetRankingsTournamentsTournamentIdRankingsGetResponses,
  GetRankingsTournamentsTournamentIdRankingsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetRankingsTournamentsTournamentIdRankingsGetResponses,
    GetRankingsTournamentsTournamentIdRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/rankings',
    ...options,
  });

/**
 * Create Ranking
 */
export const createRankingTournamentsTournamentIdRankingsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRankingTournamentsTournamentIdRankingsPostData, ThrowOnError>,
): RequestResult<
  CreateRankingTournamentsTournamentIdRankingsPostResponses,
  CreateRankingTournamentsTournamentIdRankingsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateRankingTournamentsTournamentIdRankingsPostResponses,
    CreateRankingTournamentsTournamentIdRankingsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Ranking
 */
export const deleteRankingTournamentsTournamentIdRankingsRankingIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
    DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
  });

/**
 * Update Ranking By Id
 */
export const updateRankingByIdTournamentsTournamentIdRankingsRankingIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutData, ThrowOnError>,
): RequestResult<
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
    UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Round
 */
export const createRoundTournamentsTournamentIdRoundsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoundTournamentsTournamentIdRoundsPostData, ThrowOnError>,
): RequestResult<
  CreateRoundTournamentsTournamentIdRoundsPostResponses,
  CreateRoundTournamentsTournamentIdRoundsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateRoundTournamentsTournamentIdRoundsPostResponses,
    CreateRoundTournamentsTournamentIdRoundsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Round
 */
export const deleteRoundTournamentsTournamentIdRoundsRoundIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
    DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
  });

/**
 * Update Round By Id
 */
export const updateRoundByIdTournamentsTournamentIdRoundsRoundIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutData, ThrowOnError>,
): RequestResult<
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
    UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Schedule Matches
 */
export const scheduleMatchesTournamentsTournamentIdScheduleMatchesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostData, ThrowOnError>,
): RequestResult<
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
    ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/schedule_matches',
    ...options,
  });

/**
 * List Tournament Sponsors
 */
export const listTournamentSponsorsTournamentsTournamentIdSponsorsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListTournamentSponsorsTournamentsTournamentIdSponsorsGetData, ThrowOnError>,
): RequestResult<
  ListTournamentSponsorsTournamentsTournamentIdSponsorsGetResponses,
  ListTournamentSponsorsTournamentsTournamentIdSponsorsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListTournamentSponsorsTournamentsTournamentIdSponsorsGetResponses,
    ListTournamentSponsorsTournamentsTournamentIdSponsorsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/sponsors',
    ...options,
  });

/**
 * Create Tournament Sponsor Route
 */
export const createTournamentSponsorRouteTournamentsTournamentIdSponsorsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostResponses,
  CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostResponses,
    CreateTournamentSponsorRouteTournamentsTournamentIdSponsorsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/sponsors',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Tournament Sponsor Route
 */
export const deleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteResponses,
  DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteResponses,
    DeleteTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/sponsors/{sponsor_id}',
    ...options,
  });

/**
 * Update Tournament Sponsor Route
 */
export const updateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutResponses,
  UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutResponses,
    UpdateTournamentSponsorRouteTournamentsTournamentIdSponsorsSponsorIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/sponsors/{sponsor_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Upload Tournament Sponsor Logo
 */
export const uploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostData,
    ThrowOnError
  >,
): RequestResult<
  UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostResponses,
  UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostResponses,
    UploadTournamentSponsorLogoTournamentsTournamentIdSponsorsSponsorIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/sponsors/{sponsor_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Stage Item
 */
export const createStageItemTournamentsTournamentIdStageItemsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateStageItemTournamentsTournamentIdStageItemsPostData, ThrowOnError>,
): RequestResult<
  CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
  CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
    CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage Item
 */
export const deleteStageItemTournamentsTournamentIdStageItemsStageItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
  });

/**
 * Update Stage Item
 */
export const updateStageItemTournamentsTournamentIdStageItemsStageItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Stage Item Input
 */
export const updateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
    UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
    ThrowOnError
  > =>
    (options.client ?? client).put<
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/inputs/{stage_item_input_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Start Next Round
 */
export const startNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData,
    ThrowOnError
  >,
): RequestResult<
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
    StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/start_next_round',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Matches To Schedule
 */
export const getMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData,
    ThrowOnError
  >,
): RequestResult<
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
    GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/upcoming_matches',
    ...options,
  });

/**
 * Get Stages
 */
export const getStagesTournamentsTournamentIdStagesGet = <ThrowOnError extends boolean = false>(
  options: Options<GetStagesTournamentsTournamentIdStagesGetData, ThrowOnError>,
): RequestResult<
  GetStagesTournamentsTournamentIdStagesGetResponses,
  GetStagesTournamentsTournamentIdStagesGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetStagesTournamentsTournamentIdStagesGetResponses,
    GetStagesTournamentsTournamentIdStagesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/stages',
    ...options,
  });

/**
 * Create Stage
 */
export const createStageTournamentsTournamentIdStagesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateStageTournamentsTournamentIdStagesPostData, ThrowOnError>,
): RequestResult<
  CreateStageTournamentsTournamentIdStagesPostResponses,
  CreateStageTournamentsTournamentIdStagesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateStageTournamentsTournamentIdStagesPostResponses,
    CreateStageTournamentsTournamentIdStagesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages',
    ...options,
  });

/**
 * Activate Next Stage
 */
export const activateNextStageTournamentsTournamentIdStagesActivatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ActivateNextStageTournamentsTournamentIdStagesActivatePostData, ThrowOnError>,
): RequestResult<
  ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
    ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/activate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage
 */
export const deleteStageTournamentsTournamentIdStagesStageIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteStageTournamentsTournamentIdStagesStageIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
    DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
  });

/**
 * Update Stage
 */
export const updateStageTournamentsTournamentIdStagesStageIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStageTournamentsTournamentIdStagesStageIdPutData, ThrowOnError>,
): RequestResult<
  UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
  UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
    UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Youth Schedule
 */
export const createYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostData,
    ThrowOnError
  >,
): RequestResult<
  CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostResponses,
  CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostResponses,
    CreateYouthScheduleTournamentsTournamentIdStagesStageIdYouthSchedulePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/{stage_id}/youth_schedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Teams
 */
export const getTeamsTournamentsTournamentIdTeamsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTeamsTournamentsTournamentIdTeamsGetData, ThrowOnError>,
): RequestResult<
  GetTeamsTournamentsTournamentIdTeamsGetResponses,
  GetTeamsTournamentsTournamentIdTeamsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTeamsTournamentsTournamentIdTeamsGetResponses,
    GetTeamsTournamentsTournamentIdTeamsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/teams',
    ...options,
  });

/**
 * Create Team
 */
export const createTeamTournamentsTournamentIdTeamsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTeamTournamentsTournamentIdTeamsPostData, ThrowOnError>,
): RequestResult<
  CreateTeamTournamentsTournamentIdTeamsPostResponses,
  CreateTeamTournamentsTournamentIdTeamsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTeamTournamentsTournamentIdTeamsPostResponses,
    CreateTeamTournamentsTournamentIdTeamsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Team
 */
export const deleteTeamTournamentsTournamentIdTeamsTeamIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
    DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
  });

/**
 * Update Team By Id
 */
export const updateTeamByIdTournamentsTournamentIdTeamsTeamIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutData, ThrowOnError>,
): RequestResult<
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
    UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Team Logo
 */
export const updateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostData, ThrowOnError>,
): RequestResult<
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
    UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Multiple Teams
 */
export const createMultipleTeamsTournamentsTournamentIdTeamsMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostData, ThrowOnError>,
): RequestResult<
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
    CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get User
 */
export const getUserUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserUsersMeGetData, ThrowOnError>,
): RequestResult<GetUserUsersMeGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetUserUsersMeGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
  });

/**
 * Register User
 */
export const registerUserUsersRegisterPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserUsersRegisterPostData, ThrowOnError>,
): RequestResult<
  RegisterUserUsersRegisterPostResponses,
  RegisterUserUsersRegisterPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterUserUsersRegisterPostResponses,
    RegisterUserUsersRegisterPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Register Demo User
 */
export const registerDemoUserUsersRegisterDemoPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterDemoUserUsersRegisterDemoPostData, ThrowOnError>,
): RequestResult<
  RegisterDemoUserUsersRegisterDemoPostResponses,
  RegisterDemoUserUsersRegisterDemoPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterDemoUserUsersRegisterDemoPostResponses,
    RegisterDemoUserUsersRegisterDemoPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/register_demo',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Me
 */
export const getMeUsersUserIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMeUsersUserIdGetData, ThrowOnError>,
): RequestResult<GetMeUsersUserIdGetResponses, GetMeUsersUserIdGetErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetMeUsersUserIdGetResponses,
    GetMeUsersUserIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
  });

/**
 * Update User Details
 */
export const updateUserDetailsUsersUserIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserDetailsUsersUserIdPutData, ThrowOnError>,
): RequestResult<
  UpdateUserDetailsUsersUserIdPutResponses,
  UpdateUserDetailsUsersUserIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateUserDetailsUsersUserIdPutResponses,
    UpdateUserDetailsUsersUserIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Put User Password
 */
export const putUserPasswordUsersUserIdPasswordPut = <ThrowOnError extends boolean = false>(
  options: Options<PutUserPasswordUsersUserIdPasswordPutData, ThrowOnError>,
): RequestResult<
  PutUserPasswordUsersUserIdPasswordPutResponses,
  PutUserPasswordUsersUserIdPasswordPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutUserPasswordUsersUserIdPasswordPutResponses,
    PutUserPasswordUsersUserIdPasswordPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
